### ISSUE TITLE
Lege h2 en summary

### ISSUE THREAD

**Issue by Tolga1999** [DaanCarst/the-web-is-for-everyone-interactive-functionality#1]
https://github.com/DaanCarst/the-web-is-for-everyone-interactive-functionality/blob/8be0e7c17b39cf33ccaea7d83c903106ae818a1c/views/toolboard.ejs#L5

verwijder of vulle deze html elementen (zitten op dezelfde pagina)

**Comment by DaanCarst** [comment]
fixed
